" Written with the help of : http://amix.dk/vim/vimrc.html:w
set noswapfile
set nocompatible
set backspace=2

" Use of plugin pathogen to rule them all
filetype off
filetype plugin indent off
execute pathogen#infect()
filetype on
filetype plugin indent on
call pathogen#helptags()

" Use the wildmenu
set wildmenu 
set wildmode=longest:full,full

" search
set ignorecase

" Tabs
set expandtab
set smartindent
set shiftwidth=4
set tabstop=4

" Line numbers
set number relativenumber

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

" Prevent vim from creating backup files
set nobackup
set nowritebackup

" Shortcut to expand current folder name with %%
cabbr <expr> %% expand('%:p:h')

filetype plugin indent on
syntax enable
noremap <F12> <Esc>:syntax sync fromstart<CR>
inoremap <F12> <C-o>:syntax sync fromstart<CR>

" Associate file extentions and syntax
autocmd BufNewFile,BufRead *.less   set syntax=css
au BufNewFile,BufRead SCons* set filetype=scons

colorscheme molokai
set background=dark 

" TagBar configuration
nmap <F8> :TagbarToggle<CR>

" CTRLP configuration
let g:ctrlp_cmd = 'CtrlPBuffer'

" Language specific 
    " python
    autocmd FileType python iabbrev <buffer> pdb import pdb; pdb.set_trace()

" YouCompleteMe configuration
let g:ycm_autoclose_preview_window_after_completion = 1
