" Written with the help of : http://amix.dk/vim/vimrc.html:w
set noswapfile
set nocompatible
set backspace=2

" Load and configure Vundle.vim
set nocompatible   " be iMproved, required
filetype off       " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'majutsushi/tagbar'
Plugin 'scons.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'tpope/vim-fugitive'
Plugin 'pangloss/vim-javascript'
Plugin 'valloric/youcompleteme'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" " To ignore plugin indent changes, instead use:
" "filetype plugin on

" Use the wildmenu
set wildmenu 
set wildmode=longest:full,full

" search
set ignorecase

" Tabs
set expandtab
set smartindent
set shiftwidth=4
set tabstop=4

" Line numbers
set number relativenumber

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

" Prevent vim from creating backup files
set nobackup
set nowritebackup

" Shortcut to expand current folder name with %%
cabbr <expr> %% expand('%:p:h')

filetype plugin indent on
syntax enable
noremap <F12> <Esc>:syntax sync fromstart<CR>
inoremap <F12> <C-o>:syntax sync fromstart<CR>

" Associate file extentions and syntax
autocmd BufNewFile,BufRead *.less   set syntax=css
au BufNewFile,BufRead SCons* set filetype=scons

colorscheme molokai
set background=dark 

" TagBar configuration
nmap <F8> :TagbarToggle<CR>

" CTRLP configuration
let g:ctrlp_cmd = 'CtrlPBuffer'

" Language specific 
    " python
    autocmd FileType python iabbrev <buffer> pdb import pdb; pdb.set_trace()

" YouCompleteMe configuration
let g:ycm_autoclose_preview_window_after_completion = 1
