# Show current git branch in prompt.
function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
YELLOW="\[\033[0;33m\]"
LIGHT_GREEN="\[\033[1;32m\]"
BLUE="\[\033[1;34m\]"
LIGHT_GRAY="\[\033[0;37m\]"
PS1="$LIGHT_GREEN\u@\h $BLUE\w$YELLOW\$(parse_git_branch) $BLUE\$ $LIGHT_GRAY"

source ~/.aliases

export PATH=/usr/local/p/versions/python:$PATH
